[package]
name = "malb"
version = "1.0.1"
edition = "2021"
authors = ["Ben", "Eric"]

[dependencies]
rand = "*"
crossterm = "*"
better_term = "*"
pbars = "*"
tui = { version = "0.17.0", default-features = true }
log = "*"
tlogger = { path = "./tlogger" }